version: '3.1'
services:
  db:
    container_name: db
    image: ${LOCAL_MYSQL_DOCKER_IMAGE:-mysql:8}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${LOCAL_MYSQL_PORT:-3306}:3306
    volumes:
      - "./mysql:/var/lib/mysql"
  phpmyadmin:
    container_name: phpmyadmin
    image: ${LOCAL_PHPMYADMIN_DOCKER_IMAGE:-arm64v8/phpmyadmin:latest}
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - ${LOCAL_PHPMYADMIN_PORT:-8080}:80